### ISSUE TITLE
Definition of 'MBProgressHUD' must be imported from module 

### ISSUE THREAD

**Issue by Lucasfr10** [nickcheng/MBProgressHUD#1]
I have a code written in Objective-c and whenever I try to use 
`[MBProgressHUD showHUDAddedTo:self.view animated:YES];`
I get an weird error saying "Definition of 'MBProgressHUD' must be imported from module 'MWPhotoBrowser.MWPhotoBrowserPrivate' before it is required"

So it looks like it's a code permission issue?

On my .h file have 
`@property (assign, nonatomic) MBProgressHUD *progressHud;
`
and on .m (where the error occurs
`self.progressHud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
`

**Comment by nickcheng** [comment]
@Lucasfr10 You may came to a wrong place. https://github.com/jdg/MBProgressHUD is the official site of this library.
